// study/vuejs_guide/cli/3.숫자야구/NumberBaseball.vue
<template>
    <div>
        <h1>{{result}}</h1>
        <form @submit.prevent="onSubmitForm">
            <input ref="answer" minlength="4" maxlength="4" v-model="value" />
            <button>입력</button>
        </form>
        <div>시도: {{tries.length}}</div>
        <ul>
            <li v-for="t in tries" :key="t.try">
                <div>{{t.try}}</div>
                <div>{{t.result}}</div> 
            </li>
        </ul>
    </div>
</template>
<script>
const getNumbers = () => {
    const candidates = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    const array = [];
    for (let i = 0; i < 4; i += 1){
        const chosen = candidates.splice(Math.floor(Math.random() * (9 - i)), 1)[0];
        array.push(chosen);
    }
    return array;
}
export default {
    data() {
        return {
            answer: getNumbers(),
            tries: [], // 시도 수
            value: '', // 입력
            result: '', // 결과
        }
    },
    methods: {
        onSubmitForm() {
            if (this.value === this.answer.join('')){
                // 정답 맞췄으면
                 this.tries.push({
                try: this.value,
                result: '홈런',
            });
            this.result = '홈런';
            this.answer = getNumbers();
            this.value = '';
            this.tries = [];
            this.$refs.answer.focus();
            } else {
                // 정답 틀렸을때
                if (this.tries.length >=9) {
                    this.result = `10번 넘게 틀려서 실패! 답은 ${this.answer.join('')}이었습니다!`;
                    alert('게임을 다시 시작합니다.')
                    this.value = '';
                    this.answer = getNumbers();
                    this.tries = []; 
                    this.$refs.answer.focus();
                }
                let strike = 0;
                let ball = 0;
                // 문자열을 숫자 배열로 바꾸는 코드
                const answerArray = this.value.split('').map(v => parseInt(v));
                for (let i = 0; i < 4; i += 1){
                    if (answerArray[i] === this.answer[i]){
                        // 숫자 자릿수 모두 정답
                        strike++;
                    } else if(this.answer.includes(answerArray[i])){
                        // 숫자만 정답
                        ball++;
                    }
                }
                this.tries.push({
                    try: this.value,
                    result: `${strike} 스트라이크, ${ball} 볼입니다.`
                });
                this.value = '',
                this.$refs.answer.focus();
            }      
        }
    },
} 
</script>
<style>
    
</style>

// study/react_guide/react_study/3.숫자야구/NumberBaseball.jsx
import React, { Component, createRef } from 'react';
import Try from './Try';

// this를 쓰지 않을경우 함수를 밖으로 뺄수있다.
function getNumbers() { // 숫자 네 개를 겹치지 않고 랜덤하게 뽑는 함수
  const candidate = [1,2,3,4,5,6,7,8,9];
  const array = [];
  for (let i = 0; i < 4; i += 1) { // i 0 1 2 3  4개
    const chosen = candidate.splice(Math.floor(Math.random() * (9 - i)), 1)[0];
    array.push(chosen);
  }
  return array;
}

class NumberBaseball extends Component {
  state = {
    result: '',
    value: '',
    answer: getNumbers(), // ex: [1,3,5,7]
    tries: [], // push 쓰면 안 돼요
  };

  onSubmitForm = (e) => {
    const { value, tries, answer } = this.state;
    e.preventDefault();
    if (value === answer.join('')) {
      this.setState((prevState) => {
        return {
          result: '홈런!',
          tries: [...prevState.tries, { try: value, result: '홈런!' }],
        }
      });
      alert('게임을 다시 시작합니다!');
      this.setState({
        value: '',
        answer: getNumbers(),
        tries: [],
      });
      this.inputRef.current.focus();
    } else { // 답 틀렸으면
      const answerArray = value.split('').map((v) => parseInt(v));
      let strike = 0;
      let ball = 0;
      if (tries.length >= 9) { // 10번 이상 틀렸을 때
        this.setState({
          result: `10번 넘게 틀려서 실패! 답은 ${answer.join(',')}였습니다!`,
        });
        alert('게임을 다시 시작합니다!');
        this.setState({
          value: '',
          answer: getNumbers(),
          tries: [],
        });
        this.inputRef.current.focus();
      } else {
        for (let i = 0; i < 4; i += 1) {
          if (answerArray[i] === answer[i]) {
            strike += 1;
          } else if (answer.includes(answerArray[i])) {
            ball += 1;
          }
        }
        this.setState((prevState) => {
          return {
            tries: [...prevState.tries, { try: value, result: `${strike} 스트라이크, ${ball} 볼입니다`}],
            value: '',
          };
        });
        this.inputRef.current.focus();
      }
    }
  };

  onChangeInput = (e) => {
    console.log(this.state.answer);
    this.setState({
      value: e.target.value,
    });
  };

  inputRef = createRef(); // this.inputRef

  render() {
    const { result, value, tries } = this.state;
    return (
      <>
        <h1>{result}</h1>
        <form onSubmit={this.onSubmitForm}>
          <input ref={this.inputRef} maxLength={4} value={value} onChange={this.onChangeInput} />
        </form>
        <div>시도: {tries.length}</div>
        <ul>
          {tries.map((v, i) => {
            return (
              <Try key={`${i + 1}차 시도 :`} tryInfo={v} />
            );
          })}
        </ul>
      </>
    );
  }
}

export default NumberBaseball; // import NumberBaseball;
